### ISSUE TITLE
Command Injection in srcclr/example-ruby (master)

### ISSUE THREAD

**Issue by Guiiii-m** [srcclr/example-ruby#7]
# [Command Injection in srcclr/example-ruby (master)]()

## Issue Details

- **Vulnerability**: Command Injection
- **Severity**: High
- **Project**: srcclr/example-ruby
- **Branch**: master
- **Scan Date**: Unknown

## Issue Description
nokogiri is vulnerable to command injection. The vulnerability exists as commands can be executed in a subprocess by Ruby's `Kernel.open` through `Nokogiri::CSS::Tokenizer#load_file`.

[View more details](https://sca.veracode.com/teams/500tj3Z/issues/vulnerabilities/19192489)

**Comment by domainexpert** [comment]
Closing this issue.
