### ISSUE TITLE
Unauthorized Modification Of Variables in srcclr/example-ruby (master)

### ISSUE THREAD

**Issue by Guiiii-m** [srcclr/example-ruby#8]
# [Unauthorized Modification Of Variables in srcclr/example-ruby (master)]()

## Issue Details

- **Vulnerability**: Unauthorized Modification Of Variables
- **Severity**: Medium
- **Project**: srcclr/example-ruby
- **Branch**: master
- **Scan Date**: Unknown

## Issue Description
spree is susceptible to unauthorized modifications of variables. The vulnerability exists when a user updates an order through the API. When an admin updates an order through the API, the permitted set of attributes are updated in the server. A non-admin user can then arbitrarily update the variables by making the same API call.

[View more details](https://sca.veracode.com/teams/700tEd4/issues/vulnerabilities/22715516)

**Comment by domainexpert** [comment]
@Guiiii-m I'm closing this now.
